server:
  port: 8899
spring:
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/name/{api_url}
#          filters:
#            - AddRequestHeader=cyz,Esther
#            - AddRequestParameter=name,YuziChen
# Dubbo配置
dubbo:
  application:
    name: dubbo-springboot-demo-provider
    parameters:
      qos.enable: false
      qos.accept.foreign.ip: false
      qos.port: 33333
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace